[config]
  name = "useTimer"
  brief = """\
  Creates a timer that can be used to track a value over time.\
  """

[[config.args]]
  name = "scope"
  type = "Fusion.Scope"
  description = "The scope to store cleanup tasks."

[[config.args]]
  name = "initial"
  type = "number?"
  description = "The initial value of the timer."

[config.returns]
  type = "Timer"
  description = "A timer object."
