# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
  darklua = "seaofvoices/darklua@0.13.1"
  luau-lsp = "johnnyMorganz/luau-lsp@1.32.4"
  lune = "lune-org/lune@0.8.8"
  pesde = "daimond113/pesde@0.4.7"
  rojo = "rojo-rbx/rojo@7.4.4"
  run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"
  selene = "Kampfkarren/selene@0.27.1"
