[config]
  name = "useCoroutine"
  brief = """\
  Spawns a new coroutine that is closed once the scope is cleaned up.\
  """

  variadics = ["Args..."]

[[config.args]]
  name = "scope"
  type = "Fusion.Scope"
  description = "The scope to store clean up tasks."

[[config.args]]
  name = "resume"
  type = "thread | (Args...) -> ()"
  description = "The thread to resume, or a function to spawn."

[[config.args]]
  name = "..."
  type = "Args..."
  description = "The arguments to spawn the coroutine with."

[config.returns]
  type = "thread"
  description = "A thread that is closed once the scope is cleaned up."
