[config]
  name = "useEffect"
  brief = """\
  Perform side effects with state objects.\
  """

  variadics = ["Scope"]

[[config.args]]
  name = "scope"
  type = "Scope & Fusion.Scope"
  description = "The scope to store cleanup tasks."

[[config.args]]
  name = "callback"
  type = "(Types.Use, Scope & Types.FusionScope) -> ()"
  description = "A callback with a Use callback for tracking side effects and an inner scope scope to track cleanup tasks. This callback may not yield.."
